version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - WDS_SOCKET_PORT=3000
    ports: 
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules 
      - .:/home/node/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules 
      - .:/home/node/app
    command: ["npm", "run", "test"]
    

