name: Run tests and deploy to AWS
on:
  push:
    branches:
      - master

jobs:
  test:
      name: Run test suite
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker images
        run: docker-compose -f docker-compose-dev.yml build

      - name: Run tests
        run: CI=true docker-compose -f docker-compose-dev.yml run tests
  
  deploy:
    name: Deploy to docker and AWS
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ethernetz/learning-docker-react:latest

      - name: Generate deployment package for EB
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: learning-docker
          environment_name: Learningdocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-676753199952
          region: us-east-1
          version_label: ${{ github.run_number }}
          version_description: ${{ github.SHA }}
          deployment_package: deploy.zip